In [5]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
# magic commands
%config IPCompleter.greedy=True
%config Completer.use_jedi = False
%matplotlib inline

In [45]:
img = cv.imread(r'bin.png', cv.IMREAD_GRAYSCALE)
th_t, img_t = cv.threshold(img,0,255,cv.THRESH_BINARY+cv.THRESH_OTSU)
# 3x3 matrix with all ones, with uint8 dtype
kernel = cv.getStructuringElement(cv.MORPH_RECT, (3,3)) 
# closing_t = cv.morphologyEx(img_t, cv.MORPH_CLOSE, kernel) # Dilation followed by Erosion
cv.imwrite("bin.png", img)
print(img)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 107  61 127 195 255 255 255 255 255 255]
 [255 255 255 255 232  65   0   0   0   0  56 123 240 255 255 255]
 [255 255 255 193  27   0  31  97  97  25   0   0 147 255 255 255]
 [255 255 218   1   0  71 248 255 255 250  77   0 120 255 255 255]
 [255 255 227   4   7 242 255 255 255 255 254  10  64 255 255 255]
 [255 255 255  53   7 255 255 255 255 255 255  35   8 238 255 255]
 [255 255 255 110   0 184 255 255 255 255 192   4   0 186 255 255]
 [255 255 255 133   0  23 167 245 245 171  20   0  51 226 255 255]
 [255 255 255 197   2   0   0  31  43   0   0  90 253 255 255 255]
 [255 255 255 255 219 130  57   0   0   0 134 255 255 255 255 255]
 [255 255 255 255 255 255 255 193 115 175 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 

In [47]:
img = img < 255
print(img)

[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  Tr